"""nanohubqe: tools for Quantum ESPRESSO input generation and analysis."""

from ._version import __version__
from .deck import Atom, DeckValidationError, PWInputDeck, Species
from .parser import (
    DOSData,
    PDOSData,
    PhononDispersion,
    QERunSummary,
    parse_dos_text,
    parse_matdyn_freq_text,
    parse_pdos_text,
    parse_pw_output,
    read_bands_gnu,
    read_columns,
    read_dos,
    read_matdyn_freq,
    read_pdos,
    read_pdos_directory,
    read_pw_output,
)
from .pseudo import (
    PseudoRequirement,
    PseudoStatus,
    ensure_pseudopotentials,
    ensure_workflow_pseudopotentials,
    workflow_pseudopotential_requirements,
)
from .runner import ExecutionResult, QERunner, SubmitConfig, submit_env
from .templates import (
    aluminum_dos_pdos_workflow,
    aluminum_vc_relax,
    available_templates,
    bulk_electronic_phonon_workflow,
    graphene_relax,
    silicon_bands_dos_reference_workflow,
    silicon_bands_workflow,
    silicon_eos_workflow,
    silicon_phonon_dispersion_workflow,
    silicon_scf,
)
from .use import list_available_modules, load_qe, load_quantum_espresso, use
from .visualize import (
    plot_bands,
    plot_dos,
    plot_pdos,
    plot_phonon_dispersion,
    plot_run_curve,
    plot_total_energy,
)
from .workflow import QEStep, QEWorkflow

__all__ = [
    "Atom",
    "DeckValidationError",
    "PWInputDeck",
    "Species",
    "DOSData",
    "PDOSData",
    "PhononDispersion",
    "QERunSummary",
    "parse_dos_text",
    "parse_matdyn_freq_text",
    "parse_pdos_text",
    "parse_pw_output",
    "read_bands_gnu",
    "read_columns",
    "read_dos",
    "read_matdyn_freq",
    "read_pdos",
    "read_pdos_directory",
    "read_pw_output",
    "PseudoRequirement",
    "PseudoStatus",
    "ensure_pseudopotentials",
    "ensure_workflow_pseudopotentials",
    "workflow_pseudopotential_requirements",
    "ExecutionResult",
    "QERunner",
    "SubmitConfig",
    "submit_env",
    "aluminum_dos_pdos_workflow",
    "aluminum_vc_relax",
    "available_templates",
    "bulk_electronic_phonon_workflow",
    "graphene_relax",
    "silicon_bands_dos_reference_workflow",
    "silicon_bands_workflow",
    "silicon_eos_workflow",
    "silicon_phonon_dispersion_workflow",
    "silicon_scf",
    "use",
    "load_quantum_espresso",
    "load_qe",
    "list_available_modules",
    "plot_bands",
    "plot_dos",
    "plot_pdos",
    "plot_phonon_dispersion",
    "plot_run_curve",
    "plot_total_energy",
    "QEStep",
    "QEWorkflow",
    "__version__",
]
